### PR TITLE
Add pylint check for python files

### PR DESCRIPTION
**Pull request by sturivny**

### CODE REVIEW

**Comment by sturivny** [comment]
@bookwar @tdawson Added [pylint](https://pypi.org/project/pylint/) checks for python files.
Please, take a look. If you fine with it I'll merge it and then make a PR with changes to the `eln-rebuild.py`

**Comment by tdawson** [comment]
As far as I can tell, it looks good.
I'm a little curious why it's running on debian instead of fedora.  Not a deal breaker, but I'm just wondering if it's because of the size, configuration, or just what you prefer.

**Comment by sturivny** [comment]
Github Actions [provides](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) only Ubuntu, macOS, and Windows OS.
It is possible to run it in a Fedora container. But still, as a `base` OS will be Ubuntu :)
I can update it if that makes sense.

**Comment by tdawson** [comment]
No need to update.  I was just wondering why.

**Pull request merged**
